"""Create relationsheets

Revision ID: 3e99d1d653ac
Revises: 
Create Date: 2023-10-16 01:01:40.061547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e99d1d653ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id_country', sa.Integer(), nullable=False),
    sa.Column('name_country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_country')
    )
    op.create_table('isg',
    sa.Column('id_isg', sa.Integer(), nullable=False),
    sa.Column('name_isg', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_isg')
    )
    op.create_table('goods',
    sa.Column('id_tovar', sa.Integer(), nullable=False),
    sa.Column('name_tovar', sa.String(), nullable=False),
    sa.Column('barcod', sa.String(), nullable=True),
    sa.Column('id_country', sa.Integer(), nullable=False),
    sa.Column('id_isg', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_country'], ['country.id_country'], ),
    sa.ForeignKeyConstraint(['id_isg'], ['isg.id_isg'], ),
    sa.PrimaryKeyConstraint('id_tovar')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    op.drop_table('isg')
    op.drop_table('country')
    # ### end Alembic commands ###
