"""create_relationsheeps

Revision ID: e3f65b3aa7c3
Revises: 
Create Date: 2023-10-15 17:53:40.561009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f65b3aa7c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id_country', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_country')
    )
    op.create_table('isg',
    sa.Column('id_isg', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_isg')
    )
    op.create_table('goods',
    sa.Column('id_tovar', sa.Integer(), nullable=False),
    sa.Column('name_tovar', sa.String(), nullable=False),
    sa.Column('barcod', sa.String(), nullable=False),
    sa.Column('id_country', sa.Integer(), nullable=False),
    sa.Column('id_isg', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_country'], ['country.id_country'], ),
    sa.ForeignKeyConstraint(['id_isg'], ['isg.id_isg'], ),
    sa.PrimaryKeyConstraint('id_tovar')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    op.drop_table('isg')
    op.drop_table('country')
    # ### end Alembic commands ###
